module.exports = {

    ADMIN_LOGIN_SUCCESS         : 'Login Success',
    ADMIN_REGISTER_SUCCESS      : 'Resgister Success',
    ADMIN_LOGIN_FAILED          : 'Invalid Credentials',
    ADMIN_REGISTER_FAILED       : 'Resgistion Failed',
    FP_EMAIL_SENT               : 'Forgot password instruction has been sent to your mentioned email address',
    EMAIL_ERROR                 : 'Unable to send email at the moment',
    FORGOT_EMAIL_ERROR          : 'Mentioned email is not registered as administrator',
    PASSWORD_CHANGED            : 'Password has been changed successfully',
    INVALID_OTP                 : 'Invalid OTP',
    VALID_OTP                   : 'Valid OTP',
    INVALID_OLD                 : 'Invalid Old Password',
    PASSWORD_CHANGE_FAILED      : 'Unable to change password',
    ADMIN_DATA                  : 'Here is a admin detail',
    INVALID_ADMIN               : 'UnAuthorized Admin Request',
    SERVER_ERROR                : 'Server Error !!! Please try after some time',
    USER_UPDATED                : 'Data Updated Successfully',
    USER_UPDATE_FAILED          : 'Unable to Update Data at the moment',
    ADMIN_EXIST                 : 'Blogger with Same email is already there',
    ADMIN_CREATED               : 'Blogger has been registered successfully',
    ADMIN_CREATE_ERROR          : 'Unable to register blogger at the moment',
    ADMIN_DELETED               : 'Admin has been deleted',
    ADMIN_DELETE_ERROR          : 'Unable to delete admin at the moment',
    DASH_DATA                   : "Dashboard Data",
    INVALID_EMAIL_FORMAT        : "Invaild email-id",
    EMAIL_ALREADY               : "Email aleready exsit",
    NEW_EMAIL                   : "Please Resgistion This Email-id",
    OTP_VERIFIED                : "OTP are same",
    LEVEL_ADD_SUCCESS           : "Level Add Success",
    LEVEL_ADD_FAILED            : "Level Add Failed",
    LEVEL_NAME_ALREDY           : "Level name aleready exsit",
    LEVEL_DATA                  : 'Here is a level detail',
    INVALID_LEVEL               : 'UnAuthorized Admin Request',
    LEVEL_NAME_EXIST            : 'Blogger with Same name is already there',
    LEVEL_DATA_UPDATED          : 'Data Updated Successfully',
    LEVEL_UPDATE_FAILED         : 'Unable to Update Data at the moment',
}