module.exports = {

    USER_LOGIN_SUCCESS          : 'Login Success',
    USER_REGISTER_SUCCESS       : 'Resgister Success',
    USER_LOGIN_FAILED           : 'Invalid Credentials',
    USER_REGISTER_FAILED        : 'Resgistion Failed',
    FP_EMAIL_SENT               : 'Registation OTP has been sent to your Email Address',
    EMAIL_ERROR                 : 'Unable to send email at the moment',
    FORGOT_EMAIL_ERROR          : 'Mentioned email is not registered as administrator',
    PASSWORD_CHANGED            : 'Password has been changed successfully',
    INVALID_OTP                 : 'Invalid OTP',
    VALID_OTP                   : 'Valid OTP',
    INVALID_OLD                 : 'Invalid Old Password',
    PASSWORD_CHANGE_FAILED      : 'Unable to change password',
    ADMIN_DATA                  : 'Here is a admin detail',
    INVALID_ADMIN               : 'UnAuthorized Admin Request',
    SERVER_ERROR                : 'Server Error !!! Please try after some time',
    USER_UPDATED               : 'Data Updated Successfully',
    USER_UPDATE_FAILED         : 'Unable to Update Data at the moment',
    ADMIN_EXIST                 : 'Blogger with Same email is already there',
    ADMIN_CREATED               : 'Blogger has been registered successfully',
    ADMIN_CREATE_ERROR          : 'Unable to register blogger at the moment',
    ADMIN_DELETED               : 'Admin has been deleted',
    ADMIN_DELETE_ERROR          : 'Unable to delete admin at the moment',
    DASH_DATA                   : "Dashboard Data",
    INVALID_EMAIL_FORMAT        : "Invaild email-id",
    EMAIL_ALREADY               : "Email aleready exsit",
    NEW_EMAIL                   : "Please Resgistion This Email-id",
    OTP_VERIFIED                : "OTP are same",
}